import Navbar from '@/components/sharing/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/sharing/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DressLy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="xl:container mx-auto overflow-hidden px-8">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
